apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v4
  namespace: default
data:
    DATABASE_URL: "https://mysqlserver.somewhere.com:3306"
    DATABASE_PASSWORD: "P@SSW0rd1"
