apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config
  namespace: default
data:
  database.properties: |
    database.url: "https://mysqlserver.somewhere.com:3306"
    database.password: "P@SSW0rd1"
